version: '0.2'
sources:
- database: local
  link: ''
  type: local
  branch: master
  cache_path: ''
  cache_timestamp: ''
  filters: null
- database: poo
  link: https://github.com/qxcodepoo/arcade.git
  type: clone
  branch: master
  cache_path: ''
  cache_timestamp: '2025-12-15 10:02:10'
  filters:
  - herança
expanded:
- poo@campanha-principal
- poo@bloco_f-herança-i
tasks:
  poo@zoo: '{rate:100, human:amigo, guide:video, alone:6, study:120}'
  poo@estacionamento: '{rate:100, human:amigo, iagen:gpt, guide:video, alone:4, study:240}'
flags:
  quests: 0
  tracks: 0
  tasks: 0
  graph: 1
  xray: 0
lang: py
selected: poo@zoo
